CUSTOM_MENU_COORDINATES to SET_GAMEPLAY_CAM_MOTION_BLUR_SCALING_THIS_…
citizenfx/natives pull request #1022
Opened 2024-02-18 22:56 UTC by rainmad0

…UPDATE

Fixed wrong native name. 
Added native name.

2024-02-19 00:51 UTC, PsychoShock requested changes
Don't forget to add alias for the old names

2024-02-19 00:52 UTC, PsychoShock commented on CAM/SetGameplayCamMotionBlurScalingThisUpdate.md
> +void SET_GAMEPLAY_CAM_MOTION_BLUR_SCALING_THIS_UPDATE(float p0);
`p0` is the scaling.

2024-02-19 00:52 UTC, PsychoShock commented on CAM/SetGameplayCamMaxMotionBlurStrenghtThisUpdate.md
> +void SET_GAMEPLAY_CAM_MAX_MOTION_BLUR_STRENGTH_THIS_UPDATE(float p0);
`p0` is the max strenght

2024-02-19 00:53 UTC, AvarianKnight commented
You can't add aliases there would be collisions.

2024-02-20 19:12 UTC, PsychoShock requested changes

2024-02-20 19:12 UTC, PsychoShock commented on CAM/SetGameplayCamMaxMotionBlurStrenghtThisUpdate.md
> +void SET_GAMEPLAY_CAM_MAX_MOTION_BLUR_STRENGTH_THIS_UPDATE(float p0);
Please re-name the `p0` for `maxStrenght`

2024-02-20 19:12 UTC, PsychoShock commented on CAM/SetGameplayCamMaxMotionBlurStrenghtThisUpdate.md
> +* **p0**: the max strenght
Same for here.

2024-02-20 19:12 UTC, PsychoShock commented on CAM/SetGameplayCamMotionBlurScalingThisUpdate.md
> +void SET_GAMEPLAY_CAM_MOTION_BLUR_SCALING_THIS_UPDATE(float p0);
Please re-name the `p0` for `scaling`

2024-02-20 19:12 UTC, PsychoShock commented on CAM/SetGameplayCamMotionBlurScalingThisUpdate.md
> +* **p0**: the scaling.
Same for here.

2024-08-09 03:20 UTC, closed without merging