feat(interior): batch update interior natives
citizenfx/natives pull request #1048
Opened 2024-03-08 01:04 UTC by ook3D

2024-03-18 16:32 UTC, ook3D commented
@4mmonium hey, would you be so kind as to take a look over these? im pretty confident i did everything correctly

2024-03-18 17:20 UTC, 4mmonium commented
> @4mmonium hey, would you be so kind as to take a look over these? im pretty confident i did everything correctly

Hey there, I haven't ignored this, apologies for not giving you a reply earlier. There's quite a lot of changes done in this PR so I have been backlogging it for a bit. Will first need to check if everything is fine within the PR (such as `cs_type` declarations on parameters) and then merge locally to see if the build still compiles. There's often times where changing certain type declarations can break ABI compatibility, so we have to be careful.

Thank you for contributing and for letting me know! 😊

2024-03-18 18:04 UTC, ook3D commented
> > @4mmonium hey, would you be so kind as to take a look over these? im pretty confident i did everything correctly
> 
> Hey there, I haven't ignored this, apologies for not giving you a reply earlier. There's quite a lot of changes done in this PR so I have been backlogging it for a bit. Will first need to check if everything is fine within the PR (such as `cs_type` declarations on parameters) and then merge locally to see if the build still compiles. There's often times where changing certain type declarations can break ABI compatibility, so we have to be careful.
> 
> Thank you for contributing and for letting me know! 😊

perfect, i totally understand, thanks!

2024-03-27 19:54 UTC, PsychoShock requested changes
Hello,

This is a big PR. For nex time, try to limit every PR to 10 natives change so it can be reviewed /  merged faster. I have review probably 15 but took almost 4h, but it's a big work so it's really appreciated by community (like me). I'll continue after this changes are made. 

Thanks

2024-03-27 19:54 UTC, PsychoShock commented on INTERIOR/ActivateInteriorEntitySet.md
> +mark the entity set with the given name in this interior as being active.
`M`*

2024-03-27 19:54 UTC, PsychoShock commented on INTERIOR/DeactivateInteriorEntitySet.md
> +mark the entity set with the given name in this interior as being inactive.
`M`*

2024-03-27 19:54 UTC, PsychoShock commented on INTERIOR/DisableInterior.md
> +to turn off an interior & remove all cost associated with it.
> To deactivate an interior and eliminate all associated costs.

Would be better.

2024-03-27 19:54 UTC, PsychoShock commented on INTERIOR/EnableExteriorCullModelThisFrame.md
> +for use in multiplayer apartments which need to cull exterior shell of building etc.
> Filters out exterior objects from rendering based on their model names. Useful for multiplayer apartments requiring the removal of the exterior shell of buildings, etc.

Would be better.

2024-03-27 19:54 UTC, PsychoShock commented on INTERIOR/EnableScriptCullModelThisFrame.md
> +culls exterior objects from rendering (cascade shadows only) by model name.
> Eliminates exterior objects from rendering, specifically targeting cascade shadows, based on their model names.

Same here

2024-03-29 02:19 UTC, ook3D commented
> Hello,
> 
> This is a big PR. For nex time, try to limit every PR to 10 natives change so it can be reviewed / merged faster. I have review probably 15 but took almost 4h, but it's a big work so it's really appreciated by community (like me). I'll continue after this changes are made.
> 
> Thanks

alright sounds good, ill make smaller PRs in the future! 😄

2024-04-22 01:10 UTC, freedy69 commented
Maybe you could add to the entity set natives that you should call RefreshInterior after you apply changes to the interior for it to show up immediately? Would save some people from frustration im sure (:

2024-04-22 18:00 UTC, PsychoShock reviewed
Hey,

Can you add in the format like this:

`**Note:** Add the text there.`

For the RefreshInterior.

Thanks.

2024-04-22 18:56 UTC, ook3D commented
> Hey,
> 
> Can you add in the format like this:
> 
> `**Note:** Add the text there.`
> 
> For the RefreshInterior.
> 
> Thanks.

of course, will fix this

2024-05-05 03:13 UTC, ook3D commented
any update on this? 😄

2024-05-05 04:05 UTC, PsychoShock commented
For a better chance to be PR, you should separate them to 7-8 natives per PR. The issue right now is, if something is broken and need to be revert, it's a __lot__ of natives that will be affected too. It's also easier to review them. Just saying that on personnal experience.

2024-05-05 04:31 UTC, ook3D commented
> For a better chance to be PR, you should separate them to 7-8 natives per PR. The issue right now is, if something is broken and need to be revert, it's a **lot** of natives that will be affected too. It's also easier to review them. Just saying that on personnal experience.

fair enough

2024-08-06 20:19 UTC, AvarianKnight commented
Thank you for the PR.

We're currently not accepting batch updates to natives.

2024-08-06 20:19 UTC, closed without merging