Update SetPedConfigFlag.md
citizenfx/natives pull request #1082
Opened 2024-04-10 00:31 UTC by alberttheprince

Added the most up-to-date list of enum names to help use native documentation when setting flags.

Source:
https://alexguirre.github.io/rage-parser-dumps/dump.html?build=3095&game=gta5&search=configflags#ePedConfigFlags

Before you submit this PR, please make sure:

- You have read the contribution guidelines: Yes
- You include an example that validates your change: N/A
- Your English is grammatically correct: Yes

2024-04-21 20:51 UTC, PsychoShock requested changes
Hello,

I have left a personnal comment on this PR. Nice job. I still think a big enum like this should be moved to FiveM game docs instead since actual docs doesnt support big enums like this. I think a small work can be done to add a description on every flag if we moved there. I'll leave it to @4mmonium.

Thanks :)

2024-04-21 20:51 UTC, PsychoShock commented on PED/SetPedConfigFlag.md
> +The source for this enum is [here](https://alexguirre.github.io/rage-parser-dumps/dump.html?build=3095&game=gta5&search=ePedConfigFlags+#ePedConfigFlags).
You can remove this. External links are not really appreciated in docs.

2024-04-21 22:09 UTC, alberttheprince reviewed
Removed link as requested

2024-08-07 18:17 UTC, coalaura commented
0x4376ABF2 = CPED_CONFIG_FLAG_DisableHealthRegenerationWhenStunned

2024-08-07 19:21 UTC, AvarianKnight commented
> 0x4376ABF2 = CPED_CONFIG_FLAG_DisableHealthRegenerationWhenStunned

Going to leave this out for right now, if you want to update this in another pr feel free to do so

2024-08-07 19:21 UTC, merged