📝 Update TaskGoToCoordAnyMeans parameters
citizenfx/natives pull request #1085
Opened 2024-04-13 13:34 UTC by MonsieurBibo

After a lot of trials and errors, I found that p5 is supposed to be a vehicle and p6 is likely related to pathing for long distances.

How to test my edits: 
1) Add this code to any client side script 
 ```lua
RegisterCommand("testTask", function()
    local ped = PlayerPedId()
    local pedCoords = GetEntityCoords(ped)
    local ModelHash = `openwheel2`          
    if not IsModelInCdimage(ModelHash) then return end
    RequestModel(ModelHash)            
    while not HasModelLoaded(ModelHash) do 
        Wait(0)
    end
    local veh = CreateVehicle(ModelHash, pedCoords, 0.0, true, false)
    SetVehicleFuelLevel(veh, 100.0)
    SetVehicleDirtLevel(veh, 0.0)
   --  TriggerEvent('vehiclekeys:client:SetOwner', QBCore.Functions.GetPlate(veh)) (for qbcore)
    TaskGoToCoordAnyMeans(ped, -526.68, -1028.11, 22.66, 5.0, veh, false, 0, 0.0)
end, false)
 ```
- Go to `-583.65, -951.86, 22.89`
- Run `testTask`

2024-04-18 23:40 UTC, PsychoShock requested changes
Hello,

Nice PR. This is great work. I have left some reviews to be change in my opinion.

Thanks :)

2024-04-18 23:40 UTC, PsychoShock commented on TASK/TaskGoToCoordAnyMeans.md
> +* **p6**: Seems to be related to pathing with vehicles, maybe for long distances ?
Yes you are correct. From what I can see, R* uses to know if vehicle will do it.

2024-04-18 23:40 UTC, PsychoShock commented on TASK/TaskGoToCoordAnyMeans.md
>  * **walkingStyle**:
Can you change that? It should be the driving flag.

2024-04-18 23:40 UTC, PsychoShock commented on TASK/TaskGoToCoordAnyMeans.md
>  * **p8**:
I am not sure, but this seems to be a max range for something. Not sure what. Default seems to be `-1.0`.

2024-04-21 06:51 UTC, 4mmonium approved these changes
Approved after some improvements. Thank you for contribution, merging! 😊

2024-04-21 06:52 UTC, merged