feat(natives/object): add documentation for DELETE_OBJECT
citizenfx/natives pull request #1163
Opened 2024-08-15 22:36 UTC by ahcenezdh

* Add documentation for DELETE_OBJECT
* Add examples (Lua, JS, C#)
* A note about some entities who can't be deleted

2024-08-18 23:59 UTC, AvarianKnight requested changes
`object` is a reserved word in c#

2024-08-18 23:59 UTC, AvarianKnight commented on OBJECT/DeleteObject.md
> +int object = GetClosestObjectOfType(playerCoords.X, playerCoords.Y, playerCoords.Z, 10.0f, objectHash, true, false, false);
```suggestion
int prop = GetClosestObjectOfType(playerCoords.X, playerCoords.Y, playerCoords.Z, 10.0f, objectHash, true, false, false);
```

2024-08-18 23:59 UTC, AvarianKnight commented on OBJECT/DeleteObject.md
> +if (IsEntityAMissionEntity(object))
```suggestion
if (IsEntityAMissionEntity(prop))
```

2024-08-18 23:59 UTC, AvarianKnight commented on OBJECT/DeleteObject.md
> +    SetEntityAsMissionEntity(object, false, true);
```suggestion
    SetEntityAsMissionEntity(prop, false, true);
```

2024-08-19 00:06 UTC, ahcenezdh commented
Those exemples were tested (Lua, JS) , by deleting object in a IPL (the chair) with SetEntityAsMissionEntity

2024-08-23 23:35 UTC, AvarianKnight requested changes

2024-08-23 23:35 UTC, AvarianKnight commented on OBJECT/DeleteObject.md
> +uint objectHash = GetHashKey("v_ret_gc_chair03");
```suggestion
uint objectHash = Game.GenerateHashASCII("v_ret_gc_chair03");
```

2024-08-23 23:37 UTC, merged