Update EnableAllControlActions.md
citizenfx/natives pull request #1171
Opened 2024-08-23 17:39 UTC by Mowayyy

Added CAMERA_CONTROL enum which was unknown.

Before you submit this PR, please make sure:

- You have read the contribution guidelines
- You include an example that validates your change
- Your English is grammatically correct

2024-08-24 05:06 UTC, colistro123 reviewed
Just suggesting general feedback here, updating the parameters to `controlType` would result in inconsistencies between native parameters across files. 

To maintain consistency, it's best to leave the existing parameters as `padIndex` and introduce the new `ePadType` enum. 

If you prefer to maintain the `controlType` naming convention, you could [update all the other files](https://github.com/search?q=repo%3Acitizenfx%2Fnatives+padIndex&type=code&p=1) that reference `padIndex` to use `controlType` 😊

2024-08-25 03:42 UTC, colistro123 commented on PAD/EnableAllControlActions.md
> +void ENABLE_ALL_CONTROL_ACTIONS(int controlType);
```suggestion
void ENABLE_ALL_CONTROL_ACTIONS(int padIndex);
```

Added suggestion to change back to `padIndex` so PR validation doesn't fail on argument and parameter mismatch.

2024-08-26 17:29 UTC, AvarianKnight requested changes

2024-08-26 17:29 UTC, AvarianKnight commented on PAD/EnableAllControlActions.md
>  ```
````suggestion
```c
````

2024-08-26 17:30 UTC, merged