feat(vehicle/lights): update vehicle lights natives
citizenfx/natives pull request #1192
Opened 2024-09-13 11:18 UTC by ahcenezdh

* Update `SET_VEHICLE_HAS_UNBREAKABLE_LIGHTS`
* Update `SET_VEHICLE_HEADLIGHT_SHADOWS`
* Update `SET_VEHICLE_LIGHTS`

2024-09-13 12:00 UTC, ahcenezdh commented
Supersedes #1187

2024-09-13 17:48 UTC, AvarianKnight requested changes

2024-09-13 17:48 UTC, AvarianKnight commented on VEHICLE/SetVehicleHeadlightShadows.md
> +### JavaScript Example
```suggestion

```

2024-09-13 17:48 UTC, AvarianKnight commented on VEHICLE/SetVehicleHeadlightShadows.md
> +### C# Example
```suggestion

```

2024-09-13 17:48 UTC, AvarianKnight commented on VEHICLE/SetVehicleHeadlightShadows.md
> +enum vehicleHeadlightShadowFlags {
```suggestion
enum eVehicleHeadlightShadowFlags {
```

We should keep enum naming consistent with other natives.

2024-09-13 17:48 UTC, AvarianKnight commented on VEHICLE/SetVehicleHeadlightShadows.md
> +* **flag**: A value from `vehicleHeadlightShadowFlags` representing the desired headlight shadow flag.
```suggestion
* **flag**: A value from `eVehicleHeadlightShadowFlags` representing the desired headlight shadow flag.

```

2024-09-13 17:48 UTC, AvarianKnight commented on VEHICLE/SetVehicleLights.md
> +```
````suggestion
```c
enum eVehicleLightSetting {
    // Normal light behavior. Lights cycle through off, then low beams, then high beams.
    // Note: It's affected by day or night; high beams don't exist in daytime.
    NO_VEHICLE_LIGHT_OVERRIDE = 0,
    // Vehicle doesn't have lights, always off.
    FORCE_VEHICLE_LIGHTS_OFF  = 1, 
    // Vehicle has always-on lights.
    // During day: Cycles between low beams and high beams. 
    // At night: Cycles between low beams, low beams, and high beams.
    FORCE_VEHICLE_LIGHTS_ON   = 2,
    // Sets vehicle lights on. Behaves like normal lights (same as 0).
    SET_VEHICLE_LIGHTS_ON     = 3,
    // Sets vehicle lights off. Behaves like normal lights (same as 0).
    SET_VEHICLE_LIGHTS_OFF    = 4 
};
```

````

Keep enum naming consistent & try to make comments easier to read

2024-09-13 17:48 UTC, AvarianKnight commented on VEHICLE/SetVehicleLights.md
> +* **state**: A value from `vehicleLightSetting` representing the desired light setting.
```suggestion
* **state**: A value from `eVehicleLightSetting` representing the desired light setting.

```

2024-09-13 17:49 UTC, ahcenezdh commented on VEHICLE/SetVehicleHeadlightShadows.md
> +### JavaScript Example
Sorry was doing some test

2024-09-18 23:03 UTC, AvarianKnight requested changes

2024-09-22 16:10 UTC, merged