[PATHFIND] Updated some vehicle node natives
citizenfx/natives pull request #1199
Opened 2024-09-22 12:44 UTC by coalaura

Updated the vehicle node native's documentations.

2024-10-28 22:00 UTC, AvarianKnight requested changes

2024-10-28 22:00 UTC, AvarianKnight commented on PATHFIND/GetNthClosestVehicleNodeIdWithHeading.md
> +int GET_NTH_CLOSEST_VEHICLE_NODE_ID_WITH_HEADING(float x, float y, float z, int nthClosest, Vector3* outPosition, cs_type(float) float* outHeading, cs_type(Any) int nodeFlags, float zMeasureMult, flo
```suggestion
int GET_NTH_CLOSEST_VEHICLE_NODE_ID_WITH_HEADING(float x, float y, float z, int nthClosest, Vector3* outPosition, cs_type(float) float* outHeading, int nodeFlags, float zMeasureMult, float zTolerance);
```
Int types don't need to use cs_type

2024-12-26 22:30 UTC, coalaura commented
Anything else that needs adjustments?

2025-01-23 03:36 UTC, AvarianKnight commented on PATHFIND/GetClosestVehicleNode.md
> +```cpp
```suggestion
```c
```

2025-01-23 03:37 UTC, merged