name and documentation for 0x749DEEA2
citizenfx/natives pull request #1200
Opened 2024-09-22 12:59 UTC by coalaura

2024-10-28 22:01 UTC, AvarianKnight requested changes

2024-10-28 22:01 UTC, AvarianKnight commented on VEHICLE/GetVehicleColoursWhichCanBeSet.md
> +aliases: ["_0xEEBFC7A7EFDC35B4"]
```suggestion
aliases: ["0xEEBFC7A7EFDC35B4"]
```

2024-12-26 22:30 UTC, coalaura commented
Anything else that needs adjustments?

2025-01-23 03:37 UTC, AvarianKnight commented on VEHICLE/GetVehicleColoursWhichCanBeSet.md
> +```cpp
```suggestion
```c
```

2025-01-23 03:37 UTC, merged