name and documentation for 0xE3DB81AC
citizenfx/natives pull request #1201
Opened 2024-09-22 13:03 UTC by coalaura

2024-10-11 18:02 UTC, JayPaulinCodes approved these changes
LGTM

2024-10-28 22:02 UTC, AvarianKnight requested changes

2024-10-28 22:02 UTC, AvarianKnight commented on WEAPON/SetPedCycleVehicleWeaponsOnly.md
> +aliases: ["_0x50276EF8172F5F12"]
```suggestion
aliases: ["0x50276EF8172F5F12"]
```

2024-12-26 22:30 UTC, coalaura commented
Anything else that needs adjustments?

2025-01-23 03:38 UTC, merged