tweak(native/ad): set correct name
citizenfx/natives pull request #1208
Opened 2024-10-01 03:58 UTC by PsychoShock

2024-10-01 04:15 UTC, JayPaulinCodes requested changes

2024-10-01 04:17 UTC, ook3D commented on PAD/GetLocalPlayerAimState_2.md
>  int _GET_LOCAL_PLAYER_AIM_STATE_2();
yes

2024-10-01 04:18 UTC, ook3D commented
also, shouldnt you rename the native .md file itself?

2024-10-01 04:21 UTC, JayPaulinCodes commented on PAD/GetLocalPlayerAimState_2.md
>  int _GET_LOCAL_PLAYER_AIM_STATE_2();
Ok that's what I thought. And yes also need to update the file name like you mentioned. Good catch!

2024-10-01 16:57 UTC, PsychoShock commented
No idea why my squash of yesterday didnt comit on the PR. Should be all set, sorry for that.

2024-10-02 14:57 UTC, JayPaulinCodes requested changes

2024-10-02 14:57 UTC, JayPaulinCodes commented on PAD/GetLocalPlayerGamepadAimState.md
> +## Return value
Can you add details to outline the return values and their significance?

2024-10-28 22:12 UTC, AvarianKnight requested changes

2024-10-28 22:12 UTC, AvarianKnight commented on PAD/GetLocalPlayerGamepadAimState.md
> +```
```suggestion
Same behavior as [`GET_LOCAL_PLAYER_AIM_STATE`](#_0xBB41AFBBBC0A0287) but will also return if player using a keyboard.  
```

2025-01-23 03:16 UTC, AvarianKnight requested changes

2025-01-23 18:38 UTC, AvarianKnight commented on PAD/GetLocalPlayerGamepadAimState.md
> +aliases: ["0x59B9A7AF4C95133C", "GET_LOCAL_PLAYER_AIM_STATE_2"]
```suggestion
aliases: ["0x59B9A7AF4C95133C", "_GET_LOCAL_PLAYER_AIM_STATE_2"]
```

2025-01-23 18:38 UTC, merged