Support 3407 natives
citizenfx/natives pull request #1234
Opened 2024-12-24 18:06 UTC by spacevx

All credit goes to @gottfriedleibniz and @alloc8or for finding those natives.

This is still a WIP, needs more work to document those natives with examples. Some of them are not used in decompiled scripts

2025-01-22 17:40 UTC, AvarianKnight requested changes

2025-01-22 17:43 UTC, spacevx commented on TASK/TaskSharkCircleCoord.md
> +local function CreateShark(coords)
Sure

2025-01-23 03:08 UTC, AvarianKnight requested changes

2025-01-23 03:08 UTC, AvarianKnight commented on TASK/TaskSharkCircleCoord.md
> +    local sharkModel = GetHashKey("a_c_sharktiger")
```suggestion
CreateThread(function()
    local sharkModel = GetHashKey("a_c_sharktiger")
    RequestModel(sharkModel)
    
    while not HasModelLoaded(sharkModel) do
        Wait(0)
    end

```

2025-01-23 03:08 UTC, AvarianKnight commented on VEHICLE/SetDisableExplodeFromBodyDamageOnCollision.md
> +Prevents a vehicle from exploding upon sustaining body damage from physical collisions. Only works for planes.
```suggestion
This only works for planes.

Prevents a vehicle from exploding upon sustaining body damage from physical collisions. 
```

2025-01-23 04:44 UTC, merged