Update CreateWeaponObject.md
citizenfx/natives pull request #305
Opened 2020-05-25 07:48 UTC by jonassvensson4

I added some examples to make it more clear for people that it's required to use the RequestWeaponAsset native before using this one. I also changed the heading param to size since it's clearly increasing the size of the weapon and not changing the heading. 

Had this set to 8.0, you could imagine what 360 "degrees" would look like ;)
https://i.imgur.com/FKPt52J.png

2020-05-25 08:02 UTC, smallo92 commented
If you are showing people how to use it, you should tell them the right way ;)
```lua
local weapon = `WEAPON_ASSAULTRIFLE`
RequestWeaponAsset(weapon)
while not HasWeaponAssetLoaded(weapon) do
    Wait(0)
end

local coords = GetEntityCoords(PlayerPedId())
CreateWeaponObject(weapon, 0, coords.xyz)
```

2020-05-25 08:31 UTC, jonassvensson4 commented
> If you are showing people how to use it, you should tell them the right way ;)
> 
> ```lua
> local weapon = `WEAPON_ASSAULTRIFLE`
> RequestWeaponAsset(weapon)
> while not HasWeaponAssetLoaded(weapon) do
>     Wait(0)
> end
> 
> local coords = GetEntityCoords(PlayerPedId())
> CreateWeaponObject(weapon, 0, coords.xyz)
> ```

You're right, it was wrong of me to assume people would understand that :) I wanted to keep it small and compact. I've added your example and fixed the javascript example

2020-05-25 18:26 UTC, sgottelk commented on WEAPON/CreateWeaponObject.md
> +```
code fence here is unnecessary

2020-05-26 16:10 UTC, jonassvensson4 commented
Alright I removed the code fence. I assume you didn't mean that the entire comment was uneccessary. I can remove it of course, I just think it's good to be overclear about it.

2020-10-12 15:05 UTC, technetium-cfx requested changes

2020-10-12 15:05 UTC, technetium-cfx commented on WEAPON/CreateWeaponObject.md
> +CreateWeaponObject(weapon, 0, coords.xyz)
`.xyx` is not necessary.

2020-10-12 15:30 UTC, closed without merging