Update SetMpGamerTagColour.md and SetMpGamerTagHealthBarColour.md
citizenfx/natives pull request #371
Opened 2020-10-18 19:41 UTC by Immodicus

Please let me know if there's anything you'd like me to change.

2020-11-12 23:21 UTC, technetium-cfx requested changes

2020-11-12 23:21 UTC, technetium-cfx commented on HUD/SetMpGamerTagColour.md
>  ```
You can remove the codefence. This is only used for NativeDB imports.

2020-11-12 23:21 UTC, technetium-cfx commented on HUD/SetMpGamerTagColour.md
> +* **gamerTagId**: a gamerTagId obtained using  for example: https://runtime.fivem.net/doc/natives/?_0xBFEFE3321A3F5015
Please use markdown style links as such: `[text](link)`

2020-11-12 23:21 UTC, technetium-cfx commented on HUD/SetMpGamerTagColour.md
> +```lua
We prefer Lua examples to come before C# (and JS)

2020-11-12 23:21 UTC, technetium-cfx commented on HUD/SetMpGamerTagColour.md
> +* **hudColorIndex**: a hud colour index, see the full list here: pastebin.com/d9aHPbXN
Color and colour? Stick to `color` 🙂

2020-11-15 22:52 UTC, Immodicus commented
Thank you for your feedback!

2021-05-10 21:03 UTC, closed without merging