Extra ghost and relationship natives
citizenfx/natives pull request #445
Opened 2021-04-06 04:48 UTC by Nexxed

Forwarded from Gottfried, see [this](https://github.com/gottfriedleibniz/gta5-nativedb-data/commit/b348038e5a94369a436b6fd9550128da4a94b883) for the source.

2021-04-15 15:21 UTC, PichotM commented on NETWORK/NetworkSetEntityGhostedWithOwner.md
> +* **alpha**:
wrong parameter :o

2021-04-15 16:13 UTC, Nexxed commented on NETWORK/NetworkSetEntityGhostedWithOwner.md
> +* **alpha**:
Fixedededed

2021-04-17 12:57 UTC, blattersturm requested changes

2021-04-17 12:57 UTC, blattersturm commented on NETWORK/ResetGhostedEntityAlpha.md
> +## Parameters
> Verifying NETWORK/ResetGhostedEntityAlpha.md
> ParseError: No parameter list in "Parameters" heading.

If no parameters are present, there should not be a parameters section.

Same goes for return values. I'm not sure why you added these when renaming?

2021-04-17 12:57 UTC, blattersturm commented on NETWORK/SetGhostedEntityAlpha.md
> +## Return value
Another `Return value` section.

2021-04-17 12:57 UTC, blattersturm commented on NETWORK/SetRelationshipToPlayer.md
> +## Return value
Yet again.

2021-04-17 12:57 UTC, blattersturm commented on PED/SetRelationshipGroupDontAffectWantedLevel.md
> +void _SET_RELATIONSHIP_GROUP_DONT_AFFECT_WANTED_LEVEL(Hash group, BOOL p1);
Changed `Any` type to something else which would break ABI compat _if_ anyone uses this native already. Since it's likely not the case, ~fine.

2021-04-17 12:57 UTC, blattersturm commented on PED/SetRelationshipGroupDontAffectWantedLevel.md
> +## _SET_RELATIONSHIP_GROUP_DONT_AFFECT_WANTED_LEVEL
'group don't affect' -> grammar, does

2021-04-17 12:57 UTC, blattersturm commented on PED/SetRelationshipGroupDontAffectWantedLevel.md
> +## Return value
'Return value' strikes again.

2021-04-17 12:57 UTC, blattersturm commented on NETWORK/NetworkSetEntityGhostedWithOwner.md
> +## Return value
R E T U R N  V A L U E

2021-04-17 12:57 UTC, blattersturm commented on NETWORK/NetworkSetEntityGhostedWithOwner.md
> +
Many newlines!

2021-04-17 12:57 UTC, blattersturm commented on NETWORK/SetRelationshipToPlayer.md
> +* **value**: The ghost value?
`?`

2021-04-17 12:57 UTC, blattersturm commented on NETWORK/SetRelationshipToPlayer.md
> +void _SET_RELATIONSHIP_TO_PLAYER(Player player, BOOL value);
If it's related to ghost.. maybe mention that?

2021-04-17 12:57 UTC, blattersturm commented on NETWORK/SetRelationshipToPlayer.md
> +According to Gottfried, the name is between `_SET_RELATIONSHIP_GROUP_DONT_AFFECT_WANTED_LEVEL` and `SET_ROADS_BACK_TO_ORIGINAL`.
> names in formal docs

2021-04-17 12:58 UTC, blattersturm commented
Doesn't build.

2021-05-10 21:03 UTC, closed without merging