added small note to RENDER_SCRIPT_CAMS
citizenfx/natives pull request #497
Opened 2021-07-03 20:04 UTC by tabarra

Example of the issue: using easing out of freecam when you have kashacters or.

2021-09-24 15:41 UTC, technetium-cfx commented
Would be best to figure out more detail on these parameters, this doesn't really help us understand what they are for.

2021-09-25 05:10 UTC, tabarra commented
@Poggicek /\ maybe?

2022-03-12 14:53 UTC, stannum-cfx requested changes

2022-03-12 14:53 UTC, stannum-cfx commented on CAM/RenderScriptCams.md
> +Note: if you are having issues with weird camera ease start positions, try setting p3 and p4 to `true`.
This line needs to be moved up to above the Parameters section to work correctly in the description. Also please remove the code blocks from the description.

2022-05-06 12:46 UTC, stannum-cfx commented
Closing this due to inactivity, feel free to resolve the comments above and republish this PR.

2022-05-06 12:46 UTC, closed without merging