Update SetFloatingHelpTextStyle.md
citizenfx/natives pull request #500
Opened 2021-07-09 07:50 UTC by promraungdet

2021-07-09 16:03 UTC, blattersturm requested changes
Please use the correct syntax. This would fail the build!

2021-07-09 16:03 UTC, blattersturm commented on HUD/SetFloatingHelpTextStyle.md
> +void SET_FLOATING_HELP_TEXT_STYLE(Any p0, Any p1, hudColorIndex --[[ integer ]], Any p3, placement --[[ integer ]], ArrowPosition --[[ integer ]]);
Incorrect syntax. See the code block: C. Not some weird Lua.

2021-07-09 16:03 UTC, blattersturm commented on HUD/SetFloatingHelpTextStyle.md
> -## Parameters
Why remove the entire Parameters section?

2021-07-09 16:03 UTC, blattersturm commented on HUD/SetFloatingHelpTextStyle.md
> +Example
...?

2021-09-24 15:45 UTC, technetium-cfx commented
No updates; closing.

2021-09-24 15:45 UTC, closed without merging