Update N_0xd6ade981781fca09.md
citizenfx/natives pull request #505
Opened 2021-07-09 17:26 UTC by crocodildos

2021-07-09 17:27 UTC, technetium-cfx commented
Could you please review the contribution guidelines and open a single PR for your changes? All of these are incorrect :/

2021-09-24 16:04 UTC, Disquse commented on MOBILE/CellCamSetHeadPitch.md
> +void CELL_CAM_SET_HEAD_PITCH(float p0);
There should be `_` prefix too.

2022-03-12 14:48 UTC, stannum-cfx requested changes
As mentioned by Disquse, native name should be prefixed by `_`

2022-03-12 14:48 UTC, stannum-cfx commented on MOBILE/CellCamSetHeadPitch.md
> +```
Please don't use code blocks for descriptions.

2022-03-12 19:23 UTC, merged