add documentation for DISABLE_VEHICLE_WEAPON
citizenfx/natives pull request #587
Opened 2021-11-09 07:32 UTC by 0xLuca

documented own research, better than "how does this work ???"

2021-11-09 08:42 UTC, smallo92 commented
I wouldn't recommend to linking to the website of the competition, instead I would advise also submitting a PR to the docs website documenting the stuff there yourself, or simply to a pastebin with the information in it.

2022-03-12 14:19 UTC, stannum-cfx requested changes

2022-03-12 14:19 UTC, stannum-cfx commented on VEHICLE/DisableVehicleWeapon.md
> +* **weaponHash**: The hash key of the weapon (vehicle weapons can be found here: https://wiki.rage.mp/index.php?title=Weapons#Vehicle_weapon_names)
As suggested by Smallo, please refer only to the FiveM docs for such references.

2022-05-05 18:52 UTC, stannum-cfx commented
Closing due to inactivity, please feel free to re-open the PR if the requested changes have been made.

2022-05-05 18:52 UTC, closed without merging