Update GetVehiclePlateType.md
citizenfx/natives pull request #588
Opened 2021-11-10 11:24 UTC by Kanzia-WOT

Added returned values for reference of others

2021-11-17 19:54 UTC, PsychoShock approved these changes
By looking into decompiled files, I have only found this returning "1" so I don't think it can return this. I have done multiples tests with vanilla cars and none has return "1". All the rest is okay :)

![image](https://user-images.githubusercontent.com/94499608/142272741-2f8d103a-8854-49b5-9a1b-bf88416898da.png)

2021-11-17 20:03 UTC, PsychoShock commented
Note also that the native returns "0" when the player is not in a vehicle

2021-11-17 20:23 UTC, gottfriedleibniz commented
Reference/use the enum stored in gamecode:

```c
enum eVehiclePlateType
{
	VPT_FRONT_AND_BACK_PLATES = 0,
	VPT_FRONT_PLATES = 1,
	VPT_BACK_PLATES = 2,
	VPT_NONE = 3,
};
```

Just ensure to wrap the above in codeblocks in the markdown.

2022-01-22 11:23 UTC, stannum-cfx requested changes

2022-01-22 11:23 UTC, stannum-cfx commented on VEHICLE/GetVehiclePlateType.md
> +```
Please remove the code block from the description. ([example template](https://github.com/citizenfx/natives/blob/master/.github/CONTRIBUTING.md#example-documentation))

2022-03-12 18:27 UTC, merged