Update SetMpGamerTagEnabled.md
citizenfx/natives pull request #638
Opened 2022-02-15 10:59 UTC by TomStilson

Corrected the native name and make it more precise.

2022-02-15 12:05 UTC, jaymo1011 requested changes
Thanks for documenting! :)

2022-02-15 15:50 UTC, TomStilson commented on HUD/SetMpGamerTagEnabled.md
> +Toggles all elements for the gamer tag provided.
Got it, thanks!

2022-02-15 15:51 UTC, TomStilson commented on HUD/SetMpGamerTagEnabled.md
> +* **toggle**: Set to ```true``` to enable all elements for the gamer tag, ```false``` to disable all elements.
Got it, thank you!

2022-03-12 13:18 UTC, stannum-cfx requested changes
Merge conflicts should be fixed before merging.

Also, since this native has a known Joaat hash, someone might be able to brute force the actual name so we don't have to keep adding more aliases? This isn't mandatory, but would be nice.

2022-03-16 14:52 UTC, closed without merging