Update SetWeaponDamageModifierThisFrame.md
citizenfx/natives pull request #639
Opened 2022-02-15 21:30 UTC by orel56000

This native does not need to be called every frame, IDK why someone changed its name to be this...

2022-02-15 21:32 UTC, AvarianKnight commented
This doesn't change the file name or add any aliases?

2022-02-15 21:34 UTC, orel56000 commented
> This doesn't change the file name or add any aliases?

No, as I don't know how to do it, so I guess someone should fix it. even more, this should just return to what it used to be, as the name I purposed was the original, which was more correct than this.

2022-03-12 13:16 UTC, stannum-cfx requested changes
File name needs to be changed accordingly, aliases also need to be fixed.
For more information, see [this](https://github.com/citizenfx/natives/blob/master/.github/CONTRIBUTING.md)

2022-03-12 13:16 UTC, stannum-cfx commented on WEAPON/SetWeaponDamageModifierThisFrame.md
>  Citizen.CreateThread(function()
Creating threads shouldn't be necessary if you're not planning on running loops that require delays.

2022-03-12 17:56 UTC, merged