Update SetEntityAlpha
citizenfx/natives pull request #820
Opened 2022-09-29 00:15 UTC by regalonefour

Found out while messing with this native that it will make objects that do not have skin transparent, almost like it's attempting to emulate some sort of subsurface scattering or other effect?

Example of a chair and shipping container:
https://i.imgur.com/FGGZPtl.png
https://i.imgur.com/htbl45r.png

Before you submit this PR, please make sure:

- You have read the contribution guidelines
- You include an example that validates your change
- Your English is grammatically correct

2022-09-29 10:42 UTC, AvarianKnight commented
This isn't the proper place to put this, you should move this under description

2023-06-20 19:17 UTC, 4mmonium commented on ENTITY/SetEntityAlpha.md
> +When using the skin paramater on an entity that is not a ped, it will make the entire entity transparent at night to light sources such as the skybox. It will remain like this until the alpha is rese
Hi, this cannot be in the `## Parameters` section, it needs to be on the description, right under "This native sets the entity's alpha level.".

2023-06-20 19:18 UTC, 4mmonium requested changes
Hi, thank you for your contribution, left you some feedback🙂

2023-10-30 16:06 UTC, thorium-cfx commented
Closing this as it became stale

2023-10-30 16:06 UTC, closed without merging