Update NetworkCreateSynchronisedScene.md
citizenfx/natives pull request #822
Opened 2022-10-04 19:22 UTC by TomStilson

Create detailed documentation for this native and included an example.

Before you submit this PR, please make sure:

- You have read the contribution guidelines
- You include an example that validates your change
- Your English is grammatically correct

2023-12-26 06:23 UTC, PsychoShock requested changes

2023-12-26 06:23 UTC, PsychoShock commented on NETWORK/NetworkCreateSynchronisedScene.md
> +* **p9**: Unknown, seems to be a flag parameter.
`p9` is the phase to stop the scene.

2023-12-26 06:27 UTC, TomStilson commented on NETWORK/NetworkCreateSynchronisedScene.md
> +* **p9**: Unknown, seems to be a flag parameter.
Thank you, adding it now

2023-12-26 06:44 UTC, PsychoShock approved these changes

2024-01-29 21:07 UTC, PsychoShock commented
Didn't see `p9` was there, please replaced it for `phase` to be a complete PR.

2024-08-07 13:53 UTC, closed without merging