Add missing argument and improve documentation
citizenfx/natives pull request #830
Opened 2022-11-09 02:57 UTC by niekschoemaker

I'm not 100% sure as to what the arguments do exactly because the behavior of the native changes depending on whether oal is enabled or not, not sure what's going on there, I'm assuming this is due to the missing argument.

Without OAL it always does the non flashing fade in, and with OAL it always does the flashing fade in, even though this is not the actual missing argument.

Before you submit this PR, please make sure:

- You have read the contribution guidelines
- You include an example that validates your change
- Your English is grammatically correct

2022-11-09 17:42 UTC, niekschoemaker commented
I've validated that the argument is indeed missing from decompiled scripts, all calls I could find where in the form of:
`NETWORK::NETWORK_FADE_IN_ENTITY(iVar0, true, 1);`

2023-10-27 17:33 UTC, 4mmonium commented on NETWORK/NetworkFadeInEntity.md
> +void NETWORK_FADE_IN_ENTITY(Entity entity, BOOL flash, BOOL slow);
At this time adding new arguments in this fashion in not supported. Maybe make a note of it in the native description? Thanks!

2023-10-27 17:34 UTC, 4mmonium commented on NETWORK/NetworkFadeInEntity.md
> +* **slow**: When set to true the fadein will be a little bit slower than normal
Remove once you remove the native function declaration argument mentioned up above or it won't compile.

2023-10-27 17:35 UTC, 4mmonium requested changes
Looks good, except for the added argument you declared, that's currently not supported. Requested some changes, thank you for your contribution 😊

2023-11-01 11:01 UTC, niekschoemaker commented
> Looks good, except for the added argument you declared, that's currently not supported. Requested some changes, thank you for your contribution 😊

I've ammended the requested changes to the pull request, wasn't entirely sure which part could be done, but removed any "official" reference to the parameter and added a comment in the example and in the description about the missing parameter.

2023-11-27 17:00 UTC, 4mmonium commented on NETWORK/NetworkFadeInEntity.md
> +Note that there is another boolean parameter which is missing, when set to true the fade in will be a little bit slower.
I actually did a full research on this on Sunday, the last parameter is basically a `bSendOverNet` boolean param which basically specifies if the fade should be sent over the network or not.

2023-11-27 17:51 UTC, 4mmonium requested changes
Requested changes, but this time we know for sure what the parameters are 😊
Apologies for not researching this in full-detail earlier.

2023-11-27 17:51 UTC, 4mmonium commented on NETWORK/NetworkFadeInEntity.md
> +NetworkFadeOutEntity(PlayerPedId(), false, false)
`NetworkFadeOutEntity` has the boolean parameters reversed, first one is `bSendOverNet` and second one is `bFlash` or `flash`, I just append `b` behind it to specify it's a boolean.

I highlighted the diffs in red.
![diffs](https://github.com/citizenfx/natives/assets/38232208/3104ebf0-47d0-46a5-ae76-961435da5c7e)

What I also noticed is that fading an entity with occupants inside, such as a vehicle, will also fade the occupants, but only if they're classified as net objects (which is basically a net object method that sets the alpha for every entity within the seat manager instance of the specific vehicle entity)

![image](https://github.com/citizenfx/natives/assets/38232208/b3bbad6d-2209-4544-80b9-2c5cfcd29c34)

I improved your current example in order to demonstrate it:
```lua
RegisterCommand("fademe", function(source, args, rawCommand)
    CreateThread(function()
        local entity = GetVehiclePedIsIn(PlayerPedId())
        if entity == 0 then
            entity = PlayerPedId()
        else
            if IsVehicleSeatFree(entity, 0) then
                local playerDummy = ClonePed(PlayerPedId(), true, false, true)
                SetPedIntoVehicle(playerDummy, entity, 0)
            end
        end
       -- Last param is send over net, second is flash
        NetworkFadeOutEntity(entity, false, true)
        while NetworkIsEntityFading(entity) do
            Citizen.Wait(0)
        end
        -- Second parameter here is bSendOverNet, last one is flash
        NetworkFadeInEntity(entity, true, false)
        while NetworkIsEntityFading(entity) do
            Citizen.Wait(0)
        end
    end)
end, false)
```

Note: screenshots are provided for illustration/educational purposes only.

2024-08-09 04:36 UTC, AvarianKnight requested changes

2024-08-09 04:36 UTC, AvarianKnight commented on NETWORK/NetworkFadeInEntity.md
> +void NETWORK_FADE_IN_ENTITY(Entity entity, BOOL flash);
```suggestion
void NETWORK_FADE_IN_ENTITY(Entity entity, BOOL bNetwork);
```

2024-08-09 04:36 UTC, AvarianKnight commented on NETWORK/NetworkFadeInEntity.md
> +* **flash**: When set to true the entity will flash rapidly while fading out
```suggestion
* **network**: When set to true the entity will flash rapidly while fading out
```

2024-08-09 04:36 UTC, AvarianKnight commented on NETWORK/NetworkFadeInEntity.md
> +Note that there is another boolean parameter which is missing, when set to true the fade in will be a little bit slower.
```suggestion
**Additional Parameters**:
* **flash**: If set to true the entity will flash while fading in.
```

2024-08-09 04:36 UTC, AvarianKnight commented on NETWORK/NetworkFadeInEntity.md
> +```
```suggestion
local playerPed = PlayerPedId()

-- fade out the player while flashing them
NetworkFadeOutEntity(playerPed, true, false)
while NetworkIsEntityFading(playerPed) do
  Wait(0)
end

--- Do something like a teleport, or warp into a vehicle

-- while generally frowned upon when you can use natives, this declaration has
-- a missing parameter, which doesn't work without manually invoking.
Citizen.InvokeNative(0x1F4ED342ACEFE62D, playerPed, false, true)
while NetworkIsEntityFading(playerPed) do
  Wait(0)
end
```

2024-08-09 04:43 UTC, AvarianKnight commented on NETWORK/NetworkFadeInEntity.md
> +* **network**: When set to true the fade in will be networked.
```suggestion
* **bNetwork**: When set to true the fade in will be networked.
```

2024-08-09 19:44 UTC, merged