Complete list
citizenfx/natives pull request #847
Opened 2023-01-03 17:13 UTC by Veteranfighter

- Completed the list
- Added script occurrences
 - Added formatting for the list

Before you submit this PR, please make sure:

- You have read the contribution guidelines
- You include an example that validates your change
- Your English is grammatically correct

2023-01-03 17:27 UTC, AvarianKnight requested changes

2023-01-03 17:27 UTC, AvarianKnight commented on HUD/SetMinimapComponent.md
> +0: Los Santos' air port yellow lift-off markers. <br>
`<br>` isn't needed and wont get formatted properly, instead you should use a list
```
**Some Title**

* Some Element
* Another Element

2023-01-03 17:27 UTC, AvarianKnight commented on HUD/SetMinimapComponent.md
> +will result in green instead of blue, because the base color is yellow.
You don't need to do a new line here it will get auto formatted

2023-01-03 17:27 UTC, AvarianKnight commented on HUD/SetMinimapComponent.md
> +**0-3:** stunt_plane_races.c, traffick_air.c <br>
This is unnecessary information that end users wont need

2023-01-04 11:27 UTC, Veteranfighter commented
@AvarianKnight fixed :)

2023-01-04 21:05 UTC, AvarianKnight commented on HUD/SetMinimapComponent.md
> +will result in green instead of blue, because the base color is yellow.
You marked this as resolved but didn't remove the new like between `markers` and `will`

2023-01-05 00:50 UTC, AvarianKnight requested changes

2023-01-05 00:50 UTC, AvarianKnight commented on HUD/SetMinimapComponent.md
> +will result in green instead of blue, because the base color is yellow.
You marked this as resolved but didn't remove the new like between `markers` and `will`, letting the browser handle new lines will work better then adding them yourself

2023-01-05 00:50 UTC, AvarianKnight commented on HUD/SetMinimapComponent.md
> +Colors are being mixed, so for example using blue (HudColor: 9) on yellow lift-off markers
"The provided color will be mixed with the existing component color, for example" might be better wording and provide more context

2023-01-05 00:50 UTC, AvarianKnight commented on HUD/SetMinimapComponent.md
> +**A complete list of components ID:**
Nit: Maybe remove "complete" as more can be added in future updates

2023-01-05 21:51 UTC, Veteranfighter commented
> LGTM, you might need to [squash the commits](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together)

yeah I'm on vacation, will do on saturday!

2023-01-08 19:11 UTC, closed without merging