Updated handful of ENTITY natives documentation
citizenfx/natives pull request #896
Opened 2023-07-08 13:40 UTC by ook3D

thanks for merging my last PR with other updated natives btw! 😄  i got encouraged to do some more. i added lua examples for each of the ones i updated and filled out the description and return values when applicable. let me know if theres anything that i need to fix. thanks in advance!

2023-07-12 17:16 UTC, ahcenezdh commented on ENTITY/DeleteEntity.md
you can do a JS / C# example too if you want

2023-07-12 17:19 UTC, ahcenezdh commented on ENTITY/GetEntitySpeed.md
You can add a example to have the speed of a vehicle in km/h or miles/h based on the description of Return value

2023-07-13 17:41 UTC, ook3D commented on ENTITY/DeleteEntity.md
I would do JS and C# examples, but im not confident they will be correct, and thanks ill tweak my example

2023-07-13 17:41 UTC, ook3D commented on ENTITY/GetEntitySpeed.md
probably a good idea, thanks

2023-07-14 23:38 UTC, ahcenezdh commented on ENTITY/DeleteEntity.md
> +end
You forgot to remove a end line 25

2023-07-15 00:48 UTC, ahcenezdh commented on ENTITY/DeleteEntity.md
>  end
You forgot to remove the end line 25

2023-07-16 09:17 UTC, 4mmonium commented on ENTITY/DeleteEntity.md
> instead of doing if DoesEntityExist(....), you can do
> 
> ```lua
> if not DoesEntityExist(lightEntity) then return end
> DeleteEntity(lightEntity)
> ```
> 
> and where `prop_streetlight_01` is defined here?

I don't really agree with putting everything in a single line for code examples, it's somewhat bad for readability. While we may understand it, new users that haven't been fully exposed to the language most likely won't.

2023-07-16 09:19 UTC, 4mmonium commented on ENTITY/DeleteEntity.md
> +local lightEntity = CreateObject(light, 0, 0, 0, False, False, False)
Why are the booleans upper-cased? 🙂

2023-07-16 09:28 UTC, 4mmonium requested changes
Overall this seems fine, except for the one line conditional statements. While concise code can sometimes be desirable, I believe it may be better to prioritize readability and maintainability when writing code examples.

If you could correct that, it would be great.
Thank you for your contribution nonetheless! 🙂

2023-07-16 09:42 UTC, 4mmonium commented on ENTITY/GetEntityType.md
> +local light = GetEntityModel(prop_streetlight_01)
You should explain how to get the entity handle here before you pass it, and the `lightType` variable name makes me think there's multiple types of lights😅

Also not sure why you're getting the model, `GetEntityType` takes an entity handle.

So I would write this the following way:

```lua
local entityType = GetEntityType(PlayerPedId()) -- entityType should be '4'
```

2023-08-10 15:19 UTC, closed without merging