Explain TOGGLE_PAUSED_RENDERPHASES
citizenfx/natives pull request #912
Opened 2023-08-27 13:52 UTC by DatGuy1

Also rename variable

2023-08-30 07:44 UTC, Z3rio requested changes
Is the change from `toggle` to `rendering` really needed?
In my opinion, `toggle` does sound better.

Other than that, the descriptions looked fairly good to me.
the param description could probably be a bit better/easier to understand though, such as: `Whether to free the camera or not`

2023-12-15 11:43 UTC, 4mmonium commented
I think the original parameter name is fine, not sure why it would need a name change.
The original description needs improvements though. This function pauses game rendering when toggled off and resumes when toggled on (very similar to what the game does in single player when you press ESC to open the pause menu when the world is loaded).

2023-12-17 13:39 UTC, DatGuy1 commented
I renamed it from 'toggle' to rendering because the native name together with the argument name doesn't make it clear which status it toggles to, which is the primary function of an argument name. Does it toggle rendering on? Does it toggle paused rendering on, meaning it doesn't render?

2023-12-17 14:57 UTC, Z3rio commented
> I renamed it from 'toggle' to rendering because the native name together with the argument name doesn't make it clear which status it toggles to, which is the primary function of an argument name. Does it toggle rendering on? Does it toggle paused rendering on, meaning it doesn't render?

The variable/param name "toggle" sounds a whole lot better though, and is uniform with the rest of the documentation.
And the issue you are explaining with that name can be solved with simply adding descriptions for the native & param, which you seem to be doing in this PR.

2023-12-26 03:01 UTC, PsychoShock requested changes

2023-12-26 03:01 UTC, PsychoShock commented on GRAPHICS/TogglePausedRenderphases.md
> +Freezes the screen in its current state.
Better description would be `Switches the rendering display to exclude everything except PostFX, resulting in a frozen screen before the UI pass.`

2023-12-26 03:02 UTC, PsychoShock commented on GRAPHICS/TogglePausedRenderphases.md
> +* **rendering**: Whether to actively render the camera
This should be `toggle` since it's a "toggle" native.

2024-04-21 09:08 UTC, 4mmonium approved these changes
LGTM, merging, thank you! 😊

2024-04-21 09:09 UTC, merged