Add description to SET_PED_DENSITY_MULTIPLIER_THIS_FRAME
citizenfx/natives pull request #927
Opened 2023-10-18 03:04 UTC by Aloncheeto

Add comments for better understanding.

2023-10-18 03:05 UTC, AvarianKnight requested changes

2023-10-18 03:05 UTC, AvarianKnight commented on PED/SetPedDensityMultiplierThisFrame.md
> +```
Please don't remove the language tag

2023-10-18 03:05 UTC, AvarianKnight commented on PED/SetPedDensityMultiplierThisFrame.md
> +  - 0.0 (minimum) No peds in the street.
This should have minimum first.

2023-10-25 14:10 UTC, ahcenezdh commented
At this point, you can add examples from Lua, JS, or C#

 ```lua
-- 0.0 means no peds, while 1.0 indicates the regular density of peds.
local pedsDensityFactor = 0.0 

Citizen.CreateThread(function()
    while true do
        SetPedDensityMultiplierThisFrame(pedsDensityFactor)
        Citizen.Wait(0)    
    end
end)
```
JavaScript
```js
const pedsDensityFactor = 0.0;

setTick(() => {
    SetPedDensityMultiplierThisFrame(pedsDensityFactor(pedsDensityFactor);  
});
```

and for C# i'm not sure so i'm not going to write it

2023-12-13 08:19 UTC, 4mmonium approved these changes
Approving this PR, thank you all for your contribution 🙂

2023-12-13 09:24 UTC, merged