Update TaskVehicleDriveToCoordLongrange.md
citizenfx/natives pull request #942
Opened 2023-12-12 04:12 UTC by Wetter42

Added all possible flags! Please let me know if formatting is needed!

Before you submit this PR, please make sure:

- You have read the contribution guidelines
- You include an example that validates your change
- Your English is grammatically correct

Seriously - Please feel free to add any feedback needed here;

2023-12-12 09:02 UTC, 4mmonium requested changes
Hey, requested some changes. Thank you for your contribution, nonetheless! 🙂

2023-12-12 18:31 UTC, Wetter42 commented on TASK/TaskVehicleDriveToCoordLongrange.md
> +## Flags:
All set! Thanks! - Checked out the doc, although there's nothing there that mentions flags, or the use of enum sections....Shall I...make a pull request of that as well? LMFAOOOO

2023-12-13 17:01 UTC, Wetter42 commented
okay - I think Im ready! #roastme

2023-12-13 17:58 UTC, ahcenezdh commented
Squash your commits!

2023-12-16 23:27 UTC, Wetter42 commented
> Squash your commits!

Unfortunately, I'm using github web...I've tried doing research, but there doesn't seem to be a way to squash commits on the web-version, only cli / ghdesktop.  Would it be better if I closed this particular request, and reopened it with all of the appropriate changes? 

Please let me know! 
Thanks!

2023-12-26 13:49 UTC, PsychoShock requested changes

2023-12-26 13:49 UTC, PsychoShock commented on TASK/TaskVehicleDriveToCoordLongrange.md
> +  DF_AdjustCruiseSpeedBasedOnRoadSpeed = 16384,
This will only working on mission_cruise too.

2023-12-26 13:49 UTC, PsychoShock commented on TASK/TaskVehicleDriveToCoordLongrange.md
> +  DF_UseWanderFallbackInsteadOfStraightLine = 2048,
You could add `If pathfinding fails, navigate randomly instead of moving along a straight line.`

2024-08-07 18:17 UTC, AvarianKnight requested changes

2024-08-07 18:17 UTC, AvarianKnight commented on TASK/TaskVehicleDriveToCoordLongrange.md
> +enum EDriveBehaviorFlags {
````suggestion
```
enum eDriveBehaviorFlags {
````

2024-08-07 18:17 UTC, AvarianKnight commented on TASK/TaskVehicleDriveToCoordLongrange.md
> +
```suggestion
```

2024-08-07 18:17 UTC, AvarianKnight commented on TASK/TaskVehicleDriveToCoordLongrange.md
> +
````suggestion
```
````

2024-08-07 18:18 UTC, AvarianKnight commented on TASK/TaskVehicleDriveToCoordLongrange.md
> +```
````suggestion
```

````

2024-08-07 19:13 UTC, AvarianKnight commented on TASK/TaskVehicleDriveToCoordLongrange.md
> +```
```suggestion
```c
```

2024-08-07 19:14 UTC, merged