feat(natives/2189): update natives from the 2189 gamebuild
citizenfx/natives pull request #958
Opened 2023-12-24 16:47 UTC by ahcenezdh

Update natives from the 2189 gamebuild with names and descriptions

2023-12-26 02:54 UTC, 4mmonium requested changes
Hey so far this looks almost OK, left you some comments regarding `cs_type` usage. Thanks!

2023-12-26 02:54 UTC, 4mmonium commented on OBJECT/SetPropTintIndex.md
> +void SET_PROP_TINT_INDEX(cs_type(Any) Object object, cs_type(Any) int tint);
`Vehicle`, `Object` and other related types [here](https://github.com/citizenfx/fivem/blob/030778a167242f79e0f59cd8d9c04b970e3b75c2/ext/natives/codegen_types.lua#L16-L37) map to `int` so using `cs_type` is generally not required for those. Also not required for `Any` to `int`.

2023-12-26 02:54 UTC, 4mmonium commented on VEHICLE/SetIgnorePlanesSmallPitchChange.md
> +void SET_IGNORE_PLANES_SMALL_PITCH_CHANGE(cs_type(Any) Vehicle vehicle, cs_type(Any) BOOL ignorePitching);
Same for this, notice [this](https://github.com/citizenfx/fivem/blob/030778a167242f79e0f59cd8d9c04b970e3b75c2/ext/natives/codegen_types.lua#L16-L37).

2023-12-26 13:35 UTC, ahcenezdh commented
Hey @4mmonium happy holidays to you 🎉and should be good, if you could check my issue #961 would be awesome!

2023-12-26 21:22 UTC, 4mmonium requested changes
Couple more changes needed, guess I may have overlooked that, thanks!

2023-12-26 21:22 UTC, 4mmonium commented on PATHFIND/SetAllowStreamHeistIslandNodes.md
> +void SET_ALLOW_STREAM_HEIST_ISLAND_NODES(int type);
That parameter is actually of `bool` type, you may name it `bAllow` I suppose.

Would change to the following:
`void SET_ALLOW_STREAM_HEIST_ISLAND_NODES(cs_type(int) BOOL bAllow)`

2023-12-26 21:22 UTC, 4mmonium commented on PATHFIND/SetAllowStreamHeistIslandNodes.md
> +* **type**: Pass `1` to enable Heist Island road nodes, `0` to disable them.
Change to `true`/`false` respectively, since boolean.

2023-12-27 19:16 UTC, ahcenezdh commented
Should be good 👍

2023-12-27 23:06 UTC, ahcenezdh commented
I just removed useless return value

2024-02-05 18:16 UTC, ahcenezdh commented
Description of `SET_IGNORE_PLANES_SMALL_PITCH_CHANGE` and `SET_ALLOW_STREAM_HEIST_ISLAND_NODES` have been revised to clarify their purpose

2024-05-13 15:45 UTC, closed without merging