Add proper description for IsEntityOnScreen
citizenfx/natives pull request #964
Opened 2023-12-26 11:21 UTC by WithLithum

Adds a properly formatted description for `IsEntityOnScreen`.

I do not consider an example would be needed for this native considering how simple is the native is, and the new description means about the same thing as of the old imported description.

Feel free to edit this PR if you think something is wrong.

2023-12-26 13:06 UTC, ahcenezdh commented
You need to add the ## Return value and specify what information is returning this native

2023-12-26 13:45 UTC, PsychoShock commented on ENTITY/IsEntityOnScreen.md
> -Returns true if the entity is in between the minimum and maximum values for the 2d screen coords.
This should be on the return value instead of deleting.

2023-12-27 06:51 UTC, PsychoShock requested changes

2023-12-27 06:51 UTC, PsychoShock commented on ENTITY/IsEntityOnScreen.md
> +Returns `true` if the the entity is in between the minimum and maximum values for the 2d screen coord; otherwise, `false`.
Return value need to be after param. Please refer to https://github.com/citizenfx/natives/blob/master/.github/CONTRIBUTING.md

2023-12-27 07:42 UTC, PsychoShock approved these changes
Look's good. Please squash it [like this](https://docs.fivem.net/docs/contributing/git/squash-guide/) to make it cleaner..

2023-12-28 13:01 UTC, merged