feat(audio): batch 3 of native updates
citizenfx/natives pull request #999
Opened 2024-02-16 14:55 UTC by AvarianKnight

2024-02-18 14:04 UTC, 4mmonium requested changes
Looks good so far, you could consider this nitpicking, albeit I'm somewhat sure the alias for that other native is required.

2024-02-18 14:44 UTC, AvarianKnight commented on AUDIO/FindRadioStationIndex.md
> +The station index for the specified hash, or ?? otherwise.
This was meant to be replaced by whatever the game has as the default

2024-02-19 21:43 UTC, 4mmonium commented on AUDIO/FindRadioStationIndex.md
> +The station index for the specified hash, or ?? otherwise.
Hey there, the game returns `254` if not found.

![image](https://github.com/citizenfx/natives/assets/38232208/691b1b85-9e18-4bd6-8342-1d4486732cef)

2024-02-20 00:48 UTC, AvarianKnight commented on AUDIO/GetAmbientVoiceNameHash.md
>  aliases: ["0x5E203DA2BA15D436"]
Do natives that keep the same name need to have an alias?

I don't think the underscore ever gets used anywhere for an alias to be necessary, please correct me if I'm wrong

2024-02-20 05:27 UTC, 4mmonium commented on AUDIO/GetAmbientVoiceNameHash.md
>  aliases: ["0x5E203DA2BA15D436"]
> Do natives that keep the same name need to have an alias?
> 
> I don't think the underscore ever gets used anywhere for an alias to be necessary, please correct me if I'm wrong

That's a great question, I'm going to ask. Anyway, this is what I have found:
https://github.com/citizenfx/natives/blob/4ec7d47d236ec30b8861b1e693ee521ef807274f/CLOCK/GetUtcTime.md?plain=1#L2-L6

https://github.com/citizenfx/natives/blob/4ec7d47d236ec30b8861b1e693ee521ef807274f/DECORATOR/DecorSetFloat.md?plain=1#L2-L6

https://github.com/citizenfx/natives/blob/4ec7d47d236ec30b8861b1e693ee521ef807274f/ENTITY/GetAnimDuration.md?plain=1#L2-L6

https://github.com/citizenfx/natives/blob/4ec7d47d236ec30b8861b1e693ee521ef807274f/ENTITY/GetEntityCollisionDisabled.md?plain=1#L2-L6

https://github.com/citizenfx/natives/blob/4ec7d47d236ec30b8861b1e693ee521ef807274f/STATS/PlaystatsCrateCreated.md?plain=1#L2-L6

https://github.com/citizenfx/natives/blob/4ec7d47d236ec30b8861b1e693ee521ef807274f/STATS/PlaystatsHeistSaveCheat.md?plain=1#L2-L6

2024-02-21 19:26 UTC, 4mmonium commented on AUDIO/GetAmbientVoiceNameHash.md
>  aliases: ["0x5E203DA2BA15D436"]
@AvarianKnight Got news from thorium, apparently yes they do need any preceding name as an alias as that'll make sure the natives and enums still have them present.

Hope this clears it up for you 😊

2024-02-21 21:20 UTC, merged